## 异常处理机制

- 异常处理五个关键字 ：**try**、**catch** 、**finally**、 **throw**、 **throws** 

    ```java
    public class Test {
        public static void main(String[] args) {
            int a = 1;
            int b = 0;
    
            try {
                System.out.println(a/b);
            }
            catch (Error e){
                System.out.println("Error");
            }
            catch (ArithmeticException e){
                System.out.println("程序出现异常，变量不能为0");
            }
            finally {
                System.out.println("finally");
            }
        }
    }
    ```

    ![image-20201128231811608](https://img2020.cnblogs.com/blog/2213660/202011/2213660-20201128231813089-185721407.png)

- **try** : 定义监控区域

- **catch()** : 捕获异常，括号内为想要捕获的异常类型，可以有多个，大的异常一般会写在下面，层层递进

- **finally** ：无论能不能捕获异常都将执行，处理善后工作，可以不用 **finally** 

- 快捷键：选中代码块后 **Ctrl + Alt + T** 

    ![image-20201128231229050](https://img2020.cnblogs.com/blog/2213660/202011/2213660-20201128231230672-1810087932.png)

- **throw** ：主动抛出异常，一般在方法中使用，主动在方法中抛出异常

- **throws** ：主动在方法上抛出异常

```java
public class Test1 {
    public static void main(String[] args) {
        int a = 1;
        int b = 0;
        new Test1().test(a, b);

    }
    public void test(int a, int b){
        if (b == 0){
            throw new ArithmeticException();
        }
    }
    public void test1(int a, int b) throws ArithmeticException{
        if (b == 0){
            throw new ArithmeticException();
        }
    }
}
```

![image-20201128232123605](https://img2020.cnblogs.com/blog/2213660/202011/2213660-20201128232125176-488268101.png)

![image-20201129000813932](https://img2020.cnblogs.com/blog/2213660/202011/2213660-20201129000815440-1280013106.png)